arch: ppc64le
dist: focal
os: linux
language: shell

script:
    - export HOME_DIR=$(pwd)
    - sudo apt-get update -y && sudo apt-get install -y wget git unzip tar net-tools xz-utils curl gzip patch locales make gcc g++ openjdk-17-jdk
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-ppc64el && export PATH=$JAVA_HOME/bin:$PATH && java -version
    - sudo locale-gen en_US.UTF-8
    - # Installing Sonarqube
    - cd $HOME_DIR && wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip 
    - unzip -q sonarqube-10.5.1.90531.zip 
    - # Running SonarQube
    - sudo groupadd sonarqube
    - sudo usermod -aG sonarqube $(whoami)
    - sudo chown $(whoami):sonarqube -R $HOME_DIR/sonarqube-10.5.1.90531
    - export PATH=$PATH:$HOME_DIR/sonarqube-10.5.1.90531/bin/linux-x86-64
    - sonar.sh start && sleep 120s
    - curl http://localhost:9000/
    - # Installing sonar-scanner-cli
    - cd $HOME_DIR && wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip
    - # Modify $HOME_DIR/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner to use system JVM.
    - sed -i 's/use_embedded_jre=true/use_embedded_jre=false/g' $HOME_DIR/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner
    -Install Go and NodeJS
    - cd $HOME_DIR && wget https://go.dev/dl/go1.22.3.linux-ppc64le.tar.gz && tar -xzf go1.22.3.linux-ppc64le.tar.gz && export PATH=$HOME_DIR/go/bin:$PATH && go version
    - cd $HOME_DIR && NODE_VERSION=20.12.2 && wget https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-ppc64le.tar.gz && tar -xzf node-v$NODE_VERSION-linux-ppc64le.tar.gz && export PATH=$HOME_DIR/node-v$NODE_VERSION-linux-ppc64le/bin:$PATH && node -v
    - # Running sonar-scanner
    - cd $HOME_DIR/ && ls -al $HOME_DIR
    - $HOME_DIR/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.projectKey=gosec -Dsonar.sources=. -Dsonar.login=admin -Dsonar.password=admin  -Dsonar.kubernetes.activate=false
    - # Verifying
